name: "Happi File Sync"
description: "Syncs specified files to target repositories and creates pull requests"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  file-mappings:
    description: |
      JSON object mapping filenames to their source and destination details.
      Format: {
        "filename": {
          "sourcePath": "string",
          "sourceFilename": "string",
          "destRepo": "owner/repo",
          "destPath": "string",
          "destFilename": "string"
          "destBranch": "string"
        }
      }
    required: true
  debug:
    description: "Enable debug logging for Octokit API calls"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
