name: Release

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        
      - name: Update version branch
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          MAJOR_VERSION=$(echo ${{ steps.semantic.outputs.new_release_version }} | cut -d. -f1)
          git checkout -B v$MAJOR_VERSION
          git push -f origin v$MAJOR_VERSION